puts "The students of Villains Academy"
puts "--------------"
puts "Dr. Hannibal Lecter"
puts "Dart Vader"
puts "Nurse Ratchet"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
